project_id = "zufsbpcgcvlcdtksrzhu"

[functions.interpret-dream]
verify_jwt = false

[functions.generate-dream-image]
verify_jwt = false

[functions.suggest-tags]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.calculate-natal-chart]
verify_jwt = true

[functions.interpret-dream-with-astrology]
verify_jwt = true

[functions.check-astrological-transits]
verify_jwt = false

[functions.text-to-speech-elevenlabs]
verify_jwt = true

[functions.speech-to-text-elevenlabs]
verify_jwt = true
