project_id = "zufsbpcgcvlcdtksrzhu"

[functions.interpret-dream]
verify_jwt = false

[functions.generate-dream-image]
verify_jwt = false

[functions.suggest-tags]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
