// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zufsbpcgcvlcdtksrzhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZnNicGNnY3ZsY2R0a3Nyemh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MzQzMjgsImV4cCI6MjA3NjMxMDMyOH0.qiNGzng-uO87V6lGyVJKksRIfCNxdKwUgTvEucwUZHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});